import { Category, Brand, Product, WebsiteSettings, Coupon, ServiceablePincode } from '../types';

export const INITIAL_SETTINGS: WebsiteSettings = {
  storeName: 'ANITHA DRESSES',
  storeTagline: 'Family Fashion Shopping Mall, Ongole',
  phone: '+91 8977969989',
  whatsappNumber: '+918977969989',
  email: 'support@anithadresses.com',
  address: 'Shop No. 62 & 77, Sri Balaji Market Road, Ongole, Andhra Pradesh',
  googleMapUrl: 'https://maps.google.com/?q=Shop+No.+62+%26+77,+Sri+Balaji+Market+Road,+Ongole,+Andhra+Pradesh',
  upiId: '9618138383v@icici',
  qrCodeUrl: '/icici_qr.jpg',
  bankName: 'ICICI Bank',
  accountHolder: 'VENKATA SAI ANITHA DRESSES',
  accountNumber: '131305009133',
  ifscCode: 'ICIC0001313',
  branchName: 'Ongole Main Branch',
  gstNumber: '37AAAAA0000A1Z5',
  currency: '₹',
  defaultShippingCharge: 60,
  freeShippingThreshold: 1499,
  lowStockAlertThreshold: 5,
  socialLinks: {
    instagram: 'https://instagram.com/anithadresses',
    facebook: 'https://facebook.com/anithadresses',
    youtube: 'https://youtube.com/@anithadresses',
    whatsapp: 'https://wa.me/918977969989',
  },
  banners: {
    heroDesktop: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=1600&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&auto=format&fit=crop&q=85',
    ],
    heroMobile: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=85',
    ],
    offerBanner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
  },
  sectionToggles: {
    featuredCollections: true,
    trendingProducts: true,
    newArrivals: true,
    bestSellers: true,
    testimonials: true,
    instagramGallery: true,
    brandStory: true,
  },
  cmsText: {
    heroTitle: 'ANITHA DRESSES',
    heroSubtitle: 'Premium Family Shopping Mall - Festive & Ethnic Collections',
    aboutTitle: 'About ANITHA DRESSES',
    aboutDescription: 'ANITHA DRESSES brings you high quality fashion apparel for Men, Ladies, and Kids at wholesale boutique prices in Ongole.',
    footerText: '© 2026 ANITHA DRESSES (Family Shopping Mall, Ongole). All Rights Reserved.',
  },
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-men',
    name: 'MEN',
    slug: 'men',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
    description: 'Shirts, Pants, T-Shirts, 3 Piece Suits, 5 Piece Suits and Blazers',
    subcategories: ['Shirts', 'Pants', 'T-Shirts', 'Suits (3 Piece)', 'Suits (5 Piece)', 'Blazers'],
    itemCount: 48,
  },
  {
    id: 'cat-kids',
    name: 'KIDS',
    slug: 'kids',
    image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop&q=80',
    description: 'Frocks, Long Frocks, Boys Shirts, Jeans, Crop Tops, Party Wear, Suits, Kurta Pajama and Pancha Shirt',
    subcategories: ['Frocks', 'Long Frocks', 'Boys Shirts', 'Jeans', 'Crop Tops', 'Party Wear', 'Suits', 'Kurta Pajama', 'Pancha Shirt'],
    itemCount: 72,
  },
  {
    id: 'cat-ladies',
    name: 'LADIES',
    slug: 'ladies',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80',
    description: 'Nighties, Tops, Dress Materials, Leggings, 3 Piece Sets, Long Dresses, Sharara, Crop Tops, Half Sarees, Feeding 3 Piece Set and Feeding Tops',
    subcategories: ['Nighties', 'Tops', 'Dress Materials', 'Leggings', '3 Piece Sets', 'Long Dresses', 'Sharara', 'Crop Tops', 'Half Sarees', 'Feeding 3 Piece Set', 'Feeding Tops'],
    itemCount: 88,
  },
];

export const INITIAL_BRANDS: Brand[] = [
  { id: 'brand-1', name: 'Jockey', description: 'Premium Comfort & Innerwear' },
  { id: 'brand-2', name: 'Prisma', description: 'Quality Leggings & Bottoms' },
  { id: 'brand-3', name: 'Daisy Dee', description: 'Women Comfort Wear' },
  { id: 'brand-4', name: 'Anitha Exclusive', description: 'In-house Luxury Collection' },
  { id: 'brand-5', name: 'Fly Birds', description: 'Kids & Festive Wear' },
  { id: 'brand-6', name: 'Milton', description: 'Boutique Apparel' },
];

export const INITIAL_PRODUCTS: Product[] = [
  // MEN'S WEAR PRODUCTS
  {
    _id: 'prod-m1',
    id: 'prod-m1',
    name: 'Royal Premium Linen Cotton Formal Shirt',
    slug: 'royal-premium-linen-cotton-formal-shirt',
    category: 'MEN',
    subcategory: 'Shirts',
    brand: 'Anitha Exclusive',
    price: 1899,
    offerPrice: 1299,
    mrp: 2299,
    sku: 'AC-MEN-S01',
    barcode: '890123456101',
    hsnCode: '6205',
    description: 'Ultra comfortable 100% pure linen cotton formal shirt for business meetings and events.',
    specifications: { Fabric: 'Pure Linen Cotton', Fit: 'Slim Fit', Sleeves: 'Full Sleeves' },
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=900&auto=format&fit=crop&q=85',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Royal Blue', hex: '#1D4ED8' }, { name: 'Pure White', hex: '#FFFFFF' }],
    variants: [{ size: 'L', color: 'Royal Blue', stock: 15 }],
    stock: 25,
    lowStockThreshold: 5,
    labels: ['best_seller', 'trending'],
    featured: true,
    bestSeller: true,
    newArrival: true,
    rating: 4.8,
    reviewsCount: 22,
    createdAt: '2026-07-30T10:00:00.000Z',
  },
  {
    _id: 'prod-m2',
    id: 'prod-m2',
    name: 'Classic Slim Fit Stretch Formal Trousers',
    slug: 'classic-slim-fit-stretch-formal-trousers',
    category: 'MEN',
    subcategory: 'Pants',
    brand: 'Anitha Exclusive',
    price: 1999,
    offerPrice: 1399,
    mrp: 2499,
    sku: 'AC-MEN-P01',
    barcode: '890123456102',
    hsnCode: '6203',
    description: 'Premium viscose stretch formal trouser offering sharp executive look.',
    specifications: { Fabric: 'Viscose Stretch Blend', Pattern: 'Solid' },
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=900&auto=format&fit=crop&q=85',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Charcoal Black', hex: '#1F2937' }, { name: 'Navy Blue', hex: '#0F172A' }],
    variants: [{ size: 'L', color: 'Charcoal Black', stock: 18 }],
    stock: 30,
    lowStockThreshold: 5,
    labels: ['trending'],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.7,
    reviewsCount: 14,
    createdAt: '2026-07-30T10:00:00.000Z',
  },
  {
    _id: 'prod-m3',
    id: 'prod-m3',
    name: 'Executive 3-Piece Italian Velvet Suit Set',
    slug: 'executive-3-piece-italian-velvet-suit-set',
    category: 'MEN',
    subcategory: 'Suits (3 Piece)',
    brand: 'Milton',
    price: 7999,
    offerPrice: 5499,
    mrp: 9999,
    sku: 'AC-MEN-S3P',
    barcode: '890123456103',
    hsnCode: '6203',
    description: '3-piece designer suit set including coat, vestcoat, and trousers for grand wedding occasions.',
    specifications: { Includes: 'Blazer + Vestcoat + Trouser', Fabric: 'Italian Velvet Blend' },
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=900&auto=format&fit=crop&q=85',
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Royal Maroon', hex: '#4A0E17' }, { name: 'Midnight Black', hex: '#000000' }],
    variants: [{ size: 'L', color: 'Royal Maroon', stock: 8 }],
    stock: 12,
    lowStockThreshold: 3,
    labels: ['new', 'best_seller'],
    featured: true,
    bestSeller: true,
    newArrival: true,
    rating: 4.9,
    reviewsCount: 29,
    createdAt: '2026-07-30T10:00:00.000Z',
  },

  // KIDS WEAR PRODUCTS
  {
    _id: 'prod-k1',
    id: 'prod-k1',
    name: 'Girls Festive Zari Work Grand Party Frock',
    slug: 'girls-festive-zari-work-grand-party-frock',
    category: 'KIDS',
    subcategory: 'Frocks',
    brand: 'Fly Birds',
    price: 1999,
    offerPrice: 1399,
    mrp: 2499,
    sku: 'AC-KID-F01',
    barcode: '890123456201',
    hsnCode: '6204',
    description: 'Sparkling grand party frock for young girls suitable for birthdays and festivals.',
    specifications: { Fabric: 'Net Satin Blend', Age: '2-12 Years' },
    images: [
      'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=900&auto=format&fit=crop&q=85',
    ],
    sizes: ['Kids 24', 'Kids 28', 'Kids 32'],
    colors: [{ name: 'Magenta Pink', hex: '#BE185D' }, { name: 'Gold Yellow', hex: '#D97706' }],
    variants: [{ size: 'Kids 28', color: 'Magenta Pink', stock: 12 }],
    stock: 20,
    lowStockThreshold: 4,
    labels: ['best_seller', 'new'],
    featured: true,
    bestSeller: true,
    newArrival: true,
    rating: 4.9,
    reviewsCount: 31,
    createdAt: '2026-07-30T10:00:00.000Z',
  },
  {
    _id: 'prod-k2',
    id: 'prod-k2',
    name: 'Boys Traditional Silk Kurta Pajama & Jacket Set',
    slug: 'boys-traditional-silk-kurta-pajama-jacket-set',
    category: 'KIDS',
    subcategory: 'Kurta Pajama',
    brand: 'Fly Birds',
    price: 1899,
    offerPrice: 1299,
    mrp: 2299,
    sku: 'AC-KID-KP01',
    barcode: '890123456202',
    hsnCode: '6203',
    description: 'Ethnic dupion silk kurta pajama with embroidered jacket for young boys.',
    specifications: { Fabric: 'Dupion Silk', Age: '3-14 Years' },
    images: [
      'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=900&auto=format&fit=crop&q=85',
    ],
    sizes: ['Kids 24', 'Kids 28', 'Kids 32'],
    colors: [{ name: 'Cream Gold', hex: '#FEF08A' }, { name: 'Maroon', hex: '#4A0E17' }],
    variants: [{ size: 'Kids 28', color: 'Cream Gold', stock: 15 }],
    stock: 22,
    lowStockThreshold: 4,
    labels: ['trending'],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.8,
    reviewsCount: 19,
    createdAt: '2026-07-30T10:00:00.000Z',
  },

  // LADIES WEAR PRODUCTS
  {
    _id: 'prod-l1',
    id: 'prod-l1',
    name: 'Luxury Silk Georgette Readymade Anarkali Long Dress',
    slug: 'luxury-silk-georgette-readymade-anarkali-long-dress',
    category: 'LADIES',
    subcategory: 'Long Dresses',
    brand: 'Anitha Exclusive',
    price: 3999,
    offerPrice: 2699,
    mrp: 4999,
    sku: 'AC-LAD-LD01',
    barcode: '890123456301',
    hsnCode: '6204',
    description: 'Heavy zari embroidery georgette readymade Anarkali long dress with dupatta.',
    specifications: { Fabric: 'Heavy Faux Georgette', Work: 'Sequins Zari Thread', Flare: '4.5 Meters' },
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=900&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=900&auto=format&fit=crop&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Royal Maroon', hex: '#4A0E17' }, { name: 'Emerald Green', hex: '#064E3B' }],
    variants: [{ size: 'M', color: 'Royal Maroon', stock: 15 }],
    stock: 24,
    lowStockThreshold: 5,
    labels: ['best_seller', 'trending'],
    featured: true,
    bestSeller: true,
    newArrival: true,
    rating: 4.9,
    reviewsCount: 42,
    createdAt: '2026-07-30T10:00:00.000Z',
  },
  {
    _id: 'prod-l2',
    id: 'prod-l2',
    name: 'Designer Partywear Sharara 3-Piece Suit Set',
    slug: 'designer-partywear-sharara-3-piece-suit-set',
    category: 'LADIES',
    subcategory: 'Sharara',
    brand: 'Anitha Exclusive',
    price: 3499,
    offerPrice: 2399,
    mrp: 4299,
    sku: 'AC-LAD-SH01',
    barcode: '890123456302',
    hsnCode: '6204',
    description: 'Trending flared sharara bottom, kurti, and net dupatta set with mirror work.',
    specifications: { Includes: 'Kurti + Sharara Bottom + Dupatta', Work: 'Mirror & Zari' },
    images: [
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=900&auto=format&fit=crop&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Mustard Yellow', hex: '#CA8A04' }, { name: 'Wine Red', hex: '#881337' }],
    variants: [{ size: 'L', color: 'Mustard Yellow', stock: 10 }],
    stock: 18,
    lowStockThreshold: 4,
    labels: ['new', 'trending'],
    featured: true,
    bestSeller: false,
    newArrival: true,
    rating: 4.8,
    reviewsCount: 20,
    createdAt: '2026-07-30T10:00:00.000Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  { id: 'c-1', code: 'ANITHA10', type: 'percentage', value: 10, minOrder: 999, expiryDate: '2026-12-31', active: true },
  { id: 'c-2', code: 'FESTIVAL200', type: 'flat', value: 200, minOrder: 1999, expiryDate: '2026-12-31', active: true },
];

export const INITIAL_PINCODES: ServiceablePincode[] = [
  { _id: 'pin-1', pincode: '523001', city: 'Ongole', state: 'Andhra Pradesh', estimatedDays: '1-2 Days', additionalDeliveryFee: 0, active: true },
  { _id: 'pin-2', pincode: '520001', city: 'Vijayawada', state: 'Andhra Pradesh', estimatedDays: '2-3 Days', additionalDeliveryFee: 0, active: true },
  { _id: 'pin-3', pincode: '530001', city: 'Visakhapatnam', state: 'Andhra Pradesh', estimatedDays: '2-3 Days', additionalDeliveryFee: 0, active: true },
];
